#' Parse C-family header files using CastXML and gather data from the generated
#' XML.
#'
#' @param header A single string indicating the path of C header file.
#'
#' @param limit A flag (`TRUE`/`FALSE`) a string, or a character vector.
#'        If `TRUE`, only functions/enums/structs/unions from the directory of
#'        the input header are kept. If `FALSE`, no subsetting is performed.
#'        If a single string, it will be used as a regular expression to extract
#'        only functions/enums/structs/unions that match the pattern.
#'        If a character vector, it should be paths of directories used to
#'        constrain the scope.
#'        Default: `TRUE`.
#'
#' @param keep Either `TRUE` or `FALSE`. If `TRUE`, the XML file generated by
#'        CastXML is saved into the same directory of input header file with the
#'        same name. Default: `FALSE`.
#'
#' @param cflags A character vector of C compile flags passed to CastXML.
#'        Default: `NULL`.
#'
#' @param castxml A single string indicating the file path of the CastXML
#'        executable. Default is used the path found by `Sys.which("castxml")`.
#'
#' @return An `dynport` object.
#'
#' @note
#' Please note that function-like macros are not converted to callable entries.
#' They are reported by `port_report()` as unsupported macros.
#' See: https://github.com/CastXML/CastXML/issues/21
#' @export
port <- function(header, limit = TRUE, keep = FALSE, cflags = NULL, castxml = Sys.which("castxml")) {
    if (!is_string(castxml) || !file.exists(castxml)) {
        stop("Argument 'castxml' must be a file path of CastXML executable.")
    }
    if (!is_string(header) || !file.exists(header)) {
        stop("Argument 'header' must be a file path.")
    } else if (file_ext(header) %in% c("hpp", "hh")) {
        warning(paste(
            "Argument 'header' seems to be a C++ header file",
            "which is currently not fully supported. Parsing errors may occur."
        ))
    }
    if (!is.null(cflags) && (!is.character(cflags) || anyNA(cflags))) {
        stop("Argument 'cflags' should be NULL or a character vector without missing values.")
    }
    if (!is_flag(limit) && (!is.character(limit) || anyNA(limit))) {
        stop("Argument 'limit' should be either TRUE/FALSE or a character vector of directories.")
    }
    if (!is_flag(keep)) {
        stop("Argument 'keep' should be either TRUE or FALSE.")
    }
    cflags <- normalize_castxml_cflags(cflags)

    castxml <- normalizePath(castxml, mustWork = TRUE)
    out <- tempfile("porter-", fileext = ".xml")

    # run castxml and read the generated XML file
    proc <- system3(castxml, "--castxml-output=1", cflags, "-o", out, header)
    if (proc != 0L || !file.exists(out)) {
        stop("CastXML errors. Please check input arguments, especially 'header' and 'cflags'.")
    }

    if (keep) {
        file.copy(out, sprintf("%s.xml", tools::file_path_sans_ext(header)))
    }

    # get the directories for headers to be included
    dirs <- NULL
    pattern <- NULL
    # only consider files in the same folder as the input header file
    if (is_flag(limit)) {
        if (limit) dirs <- dirname(header)
    } else if (any(is_dir <- dir.exists(limit))) {
        dirs <- limit[is_dir]
    } else if (is_string(limit) && !is_dir) {
        # use limit as a regex
        pattern <- limit
    }
    data <- port_xml(out, dirs, pattern, clean = TRUE)
    parsed <- pull_report(data)
    data <- parsed$data
    report <- combine_reports(
        parsed$report,
        scan_castxml_function_like_macros(header, cflags, castxml, dirs, pattern)
    )

    # set empty meta data
    l <- c(
        list(
            Package = port_create_field("Package", NULL, FALSE),
            Version = port_create_field("Version", NULL, FALSE),
            Library = port_create_field("Library", NULL, FALSE)
        ),
        port_create_fields(
            PORT_FIELDS[match(names(data), PORT_FIELDS)],
            data, check = FALSE
        )
    )

    out <- structure(l, class = "dynport")
    attr(out, "report") <- report
    out
}

normalize_castxml_cflags <- function(cflags,
                                    sysname = Sys.info()[["sysname"]],
                                    sdkroot = Sys.getenv("SDKROOT", unset = ""),
                                    xcrun = Sys.which("xcrun"),
                                    xcrun_sdk = NULL) {
    if (!identical(sysname, "Darwin")) return(cflags)
    if (length(cflags) && any(startsWith(cflags, "-isysroot"))) return(cflags)

    if (nzchar(sdkroot) && dir.exists(sdkroot)) {
        return(c(cflags, "-isysroot", normalizePath(sdkroot, mustWork = TRUE)))
    }

    if (!nzchar(xcrun)) return(cflags)
    if (is.null(xcrun_sdk)) {
        xcrun_sdk <- try(system2(xcrun, "--show-sdk-path", stdout = TRUE), silent = TRUE)
    }
    if (inherits(xcrun_sdk, "try-error") || !length(xcrun_sdk) || !nzchar(xcrun_sdk[[1L]])) {
        return(cflags)
    }
    if (!dir.exists(xcrun_sdk[[1L]])) return(cflags)

    c(cflags, "-isysroot", normalizePath(xcrun_sdk[[1L]], mustWork = TRUE))
}

#' Inspect diagnostics recorded while generating a dynport
#'
#' @param port A `dynport` object created by [port()].
#' @param kind Optional diagnostic kind to filter by.
#'
#' @return A data frame with diagnostic entries, including source file and line
#'        when available.
#' @export
port_report <- function(port, kind = NULL) {
    if (!inherits(port, "dynport")) {
        stop("Argument 'port' should be a dynport object.")
    }
    report <- attr(port, "report", exact = TRUE)
    if (is.null(report)) report <- empty_report()
    if (!is.null(kind)) report <- report[report$kind %in% kind, , drop = FALSE]
    report
}

#' Validate generated function symbols against an exported symbol list
#'
#' @param port A `dynport` object created by [port()].
#' @param symbols A character vector of exported symbol names to compare
#'        against the generated `Function` and `Variadic` entries.
#' @param ... Reserved for future extensions.
#'
#' @return A data frame with symbol validation status.
#' @export
port_validate_symbols <- function(port, symbols, ...) {
    if (!inherits(port, "dynport")) {
        stop("Argument 'port' should be a dynport object.")
    }
    if (length(list(...))) {
        stop("Argument '...' is reserved for future extensions and should be empty.")
    }
    if (!is.character(symbols) || anyNA(symbols)) {
        stop("Argument 'symbols' should be a character vector without missing values.")
    }
    available_symbols <- unique(symbols)

    funs <- if (port_has(port, "Function")) port_get(port, "Function") else NULL
    vars <- if (port_has(port, "Variadic")) port_get(port, "Variadic") else NULL
    required <- data.frame(
        name = c(
            if (!is.null(funs)) funs$name else character(),
            if (!is.null(vars)) vars$name else character()
        ),
        field = c(
            rep("Function", if (!is.null(funs)) nrow(funs) else 0L),
            rep("Variadic", if (!is.null(vars)) nrow(vars) else 0L)
        ),
        stringsAsFactors = FALSE
    )
    if (!nrow(required)) {
        required$status <- character()
        return(required)
    }

    required$status <- ifelse(required$name %in% available_symbols, "available", "missing")
    required
}

#' Extract data from the XML file generated by CastXML
#'
#' @param xml A path of an XML generated using CastXML. Both the
#'        `--castxml-output` and `--output-gccxml` options are supported.
#'
#' @param dirs A character of directories used to constrain the header files to
#'        extract the data. Default: `NULL`.
#'
#' @param pattern A regular expression. If not `NULL`, only
#'        functions/enums/structs/unions match that pattern is returned.
#'        Default: `NULL`.
#'
#' @param clean If `TRUE`, the id, context and file data are kept. Otherwise,
#'        they are removed. Default: `FALSE`.
#'
#' @return A named list of six elements:
#'
#' - `Function`: function data
#' - `FuncPtr`: function pointer data
#' - `Enum`: enumeration data
#' - `Struct`: struct data
#' - `Union`: union data
#' - `File`: file data
#'
#' @keywords internal
#' @export
port_xml <- function(xml, dirs = NULL, pattern = NULL, clean = FALSE) {
    if (!"xml_document" %in% class(xml)) xml <- xml2::read_xml(xml)

    # check if the root is GCC_XML or CastXML
    if (!xml2::xml_name(xml2::xml_root(xml)) %in% c("GCC_XML", "CastXML")) {
        stop("Input XML should be generated using GCCXML or CastXML.")
    }

    # extract data from corresponding xml nodes
    files   <- proc_node_files(xml)
    fields  <- proc_node_fields(xml)
    types   <- proc_node_types(xml)
    funs    <- proc_node_funs(xml)
    enums   <- pull_report(proc_node_enums(xml, types, files))
    report  <- enums$report
    enums   <- enums$data
    structs <- proc_node_structs(xml, types, fields)
    unions  <- proc_node_unions(xml,  types, fields)

    # merge all type data to create a full list of types
    types <- merge_all_types(types, enums, structs, unions, fields)

    # get function pointers
    funptrs <- types$func

    # find base types for all function arguments and return values
    funs <- proc_type_funs(types, funs)

    report <- combine_reports(report)

    variadic <- NULL
    if (!is.null(funs)) {
        is_variadic <- funs$ellipsis
        variadic <- as_df(funs[is_variadic, , drop = FALSE])
        funs <- as_df(funs[!is_variadic, , drop = FALSE])
    }

    if (!is.null(funptrs) && "ellipsis" %in% names(funptrs)) {
        is_variadic_funptr <- funptrs$ellipsis
        if (any(is_variadic_funptr)) {
            report_file <- files$name[match(funptrs$file[is_variadic_funptr], files$id)]
            report <- combine_reports(report, new_report(
                "unsupported_variadic_funcptr",
                funptrs$name[is_variadic_funptr], report_file,
                "variadic function pointer is parsed but not written to FuncPtr"
            ))
            funptrs <- as_df(funptrs[!is_variadic_funptr, , drop = FALSE])
        }
    }

    # find base types for all struct/union members
    structs <- proc_type_structs(types, structs)
    unions  <- proc_type_unions(types, unions)
    layout <- mark_unsupported_layouts(structs, "struct", files)
    structs <- layout$data
    report <- combine_reports(report, layout$report)
    layout <- mark_unsupported_layouts(unions, "union", files)
    unions <- layout$data
    report <- combine_reports(report, layout$report)

    drop_unnamed <- function(df) {
        if (is.null(df)) return(NULL)
        as_df(df[!is.na(df$name) & nzchar(df$name), , drop = FALSE])
    }
    enums <- drop_unnamed(enums)
    structs <- drop_unnamed(structs)
    unions <- drop_unnamed(unions)
    funptrs <- drop_unnamed(funptrs)

    # only consider files in the same folder as the input header file
    if (!is.null(dirs)) {
        dirs <- normalizePath(dirs, mustWork = FALSE)
        paths <- normalizePath(dirname(files$name), mustWork = FALSE)
        is_tar <- logical(length(paths))
        for (d in dirs) is_tar <- is_parent_dir(d, paths) | is_tar
        inclu <- files$id[is_tar]

        # no matched
        if (!length(inclu)) {
            return(list(
                Function = NULL, Variadic = NULL, FuncPtr = NULL, Enum = NULL,
                Struct = NULL, Union = NULL, File = NULL
            ))
        } else {
            subset_by_file <- function(df, files) {
                if (!is.null(df)) as_df(df[df$file %in% files, ])
            }
            funs     <- subset_by_file(funs,     inclu)
            variadic <- subset_by_file(variadic, inclu)
            enums    <- subset_by_file(enums,    inclu)
            structs  <- subset_by_file(structs,  inclu)
            unions   <- subset_by_file(unions,   inclu)
            funptrs  <- subset_by_file(funptrs,  inclu)
            files   <- as_df(files[is_tar, ])
        }
    }

    if (!is.null(pattern)) {
        if (!is_string(pattern)) stop("Argument 'pattern' should be a single string.")
        subset_by_pattern <- function(df, pattern) {
            if (!is.null(df)) as_df(df[grepl(pattern, df$name), ])
        }
        funs     <- subset_by_pattern(funs,     pattern)
        variadic <- subset_by_pattern(variadic, pattern)
        enums    <- subset_by_pattern(enums,    pattern)
        structs  <- subset_by_pattern(structs,  pattern)
        unions   <- subset_by_pattern(unions,   pattern)
        funptrs  <- subset_by_pattern(funptrs,  pattern)

        if (!is.null(files)) {
            files <- files[files$id %in% unique(
                c(funs$file, variadic$file, enums$file, structs$file, unions$file, funptrs$file)), ]
        }
    }

    filtered <- filter_rdyncall_output(
        list(
            Function = funs, Variadic = variadic, FuncPtr = funptrs,
            Enum = enums, Struct = structs, Union = unions
        ),
        files
    )
    funs <- filtered$data$Function
    variadic <- filtered$data$Variadic
    funptrs <- filtered$data$FuncPtr
    enums <- filtered$data$Enum
    structs <- filtered$data$Struct
    unions <- filtered$data$Union
    report <- combine_reports(report, filtered$report)

    if (!is_flag(clean)) stop("Argument 'clean' should be either TRUE or FALSE.")
    if (clean) {
        remove_col <- function(df, cols) {
            if (is.null(df)) return(NULL)
            df[cols] <- NULL
            # for function returns
            if (!is.data.frame(df) && length(df) == 1L && names(df) == "type") {
                df <- df[[1L]]
            }
            df
        }
        funs     <- remove_col(funs,     c("id", "context", "file"))
        variadic <- remove_col(variadic, c("id", "context", "file", "ellipsis"))
        enums    <- remove_col(enums,    c("id", "context", "file"))
        structs  <- remove_col(structs,  c("id", "context", "file"))
        unions   <- remove_col(unions,   c("id", "context", "file"))
        funptrs  <- remove_col(funptrs,  c("id", "context", "file", "ellipsis"))

        clean_nested <- function(df, col, cols) {
            if (is.null(df)) return(NULL)
            df[[col]] <- lapply(df[[col]], remove_col, cols)
            df
        }
        funs     <- clean_nested(funs,     "returns",   "id")
        variadic <- clean_nested(variadic, "returns",   "id")
        funptrs  <- clean_nested(funptrs,  "returns",   "id")
        funs     <- clean_nested(funs,     "arguments", "id")
        variadic <- clean_nested(variadic, "arguments", "id")
        funptrs  <- clean_nested(funptrs,  "arguments", "id")
        structs  <- clean_nested(structs,  "members",   "id")
        unions   <- clean_nested(unions,   "members",   "id")

        if (!is.null(files)) files <- files$name
    }

    out <- list(
        Function = funs, Variadic = variadic, FuncPtr = funptrs,
        Enum = enums, Struct = structs, Union = unions,
        File = files
    )
    attr(out, "report") <- report
    out
}

# exclude data from builtin which is automatically generated by clang
proc_node_builtin <- function(xml) {
    xml2::xml_attr(xml2::xml_find_first(xml, "File[@name='<builtin>']"), "id")
}

proc_type_funs <- function(types, funs) {
    if (is.null(funs)) return(NULL)

    returns <- list(id = unique(funs$returns))
    returns$type <- lapply(returns$id, find_basetype, types = types$all)
    funs$returns <- lapply(match(funs$returns, returns$id),
        function(ind) list(id = returns$id[ind], type = returns$type[[ind]])
    )

    args <- list(id = unique(unlist(
        lapply(funs$arguments, .subset2, "type"), FALSE, FALSE)
    ))
    args$type <- lapply(args$id, find_basetype, types = types$all)
    for (i in seq_len(nrow(funs))) {
        a <- funs$arguments[[i]]
        if (!NROW(a)) next
        if (is.data.frame(a)) {
            names(a)[2] <- "id"
        } else {
            names(a) <- "id"
        }
        a$type <- args$type[match(a$id, args$id)]
        funs$arguments[[i]] <- a
    }

    funs
}

proc_type_structs <- function(types, structs) {
    if (is.null(structs)) return(NULL)

    for (i in seq_along(structs$members)) {
        if (is.null(structs$members[[i]])) next

        structs$members[[i]]$type <- lapply(
            structs$members[[i]]$type, find_basetype, types = types$all
        )
    }

    structs
}

proc_type_unions <- function(types, unions) proc_type_structs(types, unions)

find_basetype <- function(types, id, depth = Inf) {
    type <- c()
    kind <- c()
    n <- 1L

    while (n <= depth) {
        ind <- match(id, types$id)
        if (is.na(ind)) return(structure(list(type = c(), kind = c()), class = "dynporttype"))

        id <- types$type[ind]

        # After we reach those types, it is possible that the previous one
        # is a <Typedef/>.
        # In this case, remove the previous <Typedef/>
        if (length(kind) && !is.na(m <- match("def", kind))) {
            type <- type[-m]
            kind <- kind[-m]
        }

        type <- c(type, types$name[ind])
        kind <- c(kind, types$kind[ind])

        if (is.na(id)) break
        n <- n + 1L
    }

    # remove empty CastXML elaboration layers
    if (any(rem <- kind %in% c("elaborated", "struct", "union", "enum") & type == "")) {
        type <- type[!rem]
        kind <- kind[!rem]
    }

    structure(list(type = type, kind = kind), class = "dynporttype")
}

merge_all_types <- function(types, enums, structs, unions, fields) {
    types$all <- data.frame()

    if (!is.null(types$def)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$def$id, name = types$def$name,
                type = types$def$type, kind = "def"
            )
        )
    }

    if (!is.null(enums)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = enums$id, name = sprintf("<%s>", enums$name),
                type = NA_character_, kind = "enum"
            )
        )
    }

    if (!is.null(structs)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = structs$id, name = sprintf("<%s>", structs$name),
                type = NA_character_, kind = "struct"
            )
        )
    }

    if (!is.null(unions)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = unions$id, name = sprintf("<%s>", unions$name),
                type = NA_character_, kind = "union"
            )
        )
    }

    if (!is.null(types$base)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$base$id, name = types$base$name,
                type = NA_character_, kind = "base"
            )
        )
    }

    if (!is.null(types$cvqualified)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$cvqualified$id,
                name = ifelse(types$cvqualified$const == "1", "const", ""),
                type = types$cvqualified$type, kind = "cvqualified"
            )
        )
    }

    if (!is.null(types$atomic)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$atomic$id, name = "",
                type = types$atomic$type, kind = "atomic"
            )
        )
    }

    if (!is.null(types$auto)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$auto$id, name = "",
                type = NA_character_, kind = "auto"
            )
        )
    }

    if (!is.null(types$pointer)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$pointer$id,
                name = "*",
                type = types$pointer$type, kind = "pointer"
            )
        )
    }

    if (!is.null(types$offset)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$offset$id, name = "",
                type = types$offset$type, kind = "offset"
            )
        )
    }

    if (!is.null(types$reference)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$reference$id, name = "",
                type = types$reference$type, kind = "reference"
            )
        )
    }

    if (!is.null(types$rvalueref)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$rvalueref$id, name = "",
                type = types$rvalueref$type, kind = "rvalueref"
            )
        )
    }

    if (!is.null(types$array)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$array$id, name = format_array_type(types$array),
                type = types$array$type, kind = "array"
            )
        )
    }

    if (!is.null(types$elaborated)) {
        # <ElaboratedType/> only exists in CastXML not gccxml.
        # Both 'keyword' and 'qualifier' attributes are optional.
        elab <- df(
            id = types$elaborated$id,
            name = types$elaborated$qualifier,
            type = types$elaborated$type,
            kind = types$elaborated$keyword
        )
        elab$name[is.na(elab$name)] <- ""
        elab$kind[is.na(elab$kind)] <- "elaborated"

        types$all <- rbind.data.frame(types$all, elab)
    }

    if (!is.null(types$func)) {
        types$all <- rbind.data.frame(types$all,
            df(
                id = types$func$id, name = "",
                type = NA_character_, kind = "function"
            )
        )

        # Only function types directly referenced by a PointerType are written
        # as FuncPtr entries. Function-type typedefs remain in types$all so
        # chains such as PointerType -> Typedef -> FunctionType resolve to p.
        ind <- match(types$func$id, types$pointer$type)
        types$func <- types$func[!is.na(ind), , drop = FALSE]
        ind <- ind[!is.na(ind)]

        if (!nrow(types$func)) {
            types$func <- NULL
            return(types)
        }

        # there are only 2 possible ways that function pointers can appear:
        # a. in Typedef
        # b. as a member in Struct/Union
        members_list <- c(
            if (!is.null(structs)) structs$members else NULL,
            if (!is.null(unions)) unions$members else NULL
        )
        members <- if (length(members_list)) {
            do.call(rbind.data.frame, members_list)
        } else {
            df(id = character(), name = character(), type = character())
        }
        types_tmp <- df(
            type = c(types$def$type, members$type),
            name = c(types$def$name, members$name),
            file = c(types$def$file,
                fields$file[match(members$id, fields$id)]
            )
        )

        ind <- match(types$pointer$id[ind], types_tmp$type)
        types$func$name <- types_tmp$name[ind]
        types$func$file <- types_tmp$file[ind]
        types$func$name[is.na(types$func$name)] <- ""

        # check again and issue warnings if still no matched
        if (any(empty <- types$func$name == "")) {
            warning(spaste(
                "Failed to parse names for function pointers: %s.",
                .v = spaste("'%s'", .v = types$func$id[empty], .rcoll = ", ")
            ))
        }

        # process argument and return types
        types$func <- proc_type_funs(types, types$func)[
            , c("id", "name", "returns", "arguments", "ellipsis", "file")
        ]
        # to keep consistent with <Function /> type
        types$func$arguments <- lapply(types$func$arguments, as_df)
    }

    types
}

proc_node_files <- function(xml) {
    files <- node_attrs(xml, "File", c("id", "name"))
    if (is.null(files)) return(NULL)
    files[files$name != "<builtin>", ]
}

proc_node_fields <- function(xml) {
    fields <- node_attrs(xml, "Field", c("id", "name", "type", "context", "file", "offset", "bits"))

    if (!is.null(fields)) {
        fields$name[is.na(fields$name)] <- ""
        fields$offset <- bits_to_bytes(fields$offset)
        fields$bits <- as.integer(fields$bits)

        fields <- fields[
            # the following fields are generated by clang and do not have file
            # attributes
            !(
                is.na(fields$file) &
                fields$name %in% c("gp_offset", "fp_offset", "overflow_arg_area",
                    "reg_save_area", "isa", "flags", "str", "length")
            ),
        ]

        # exclude clang auto-generated data
        fields <- fields[!fields$file %in% proc_node_builtin(xml), ]
    }

    fields
}

proc_node_funs <- function(xml) {
    node_funs <- xml2::xml_find_all(xml, "Function")
    funs <- node_attrs(node_funs,
        attrs = c("id", "name", "returns", "context", "file", "static")
    )
    if (is.null(funs)) return(NULL)
    # exclude clang auto-generated data
    funs <- funs[!funs$file %in% proc_node_builtin(xml), ]

    fun_args <- node_attrs(node_funs, "Argument", c("name", "type"), df = FALSE)
    funs$arguments <- lapply(fun_args, function(args) {
        # it is possible that CastXML failed to extract argument names
        if (!length(args$type)) return(NULL)
        if (anyNA(args$name)) {
            mis <- is.na(args$name)

            # use this letters to generate random argument names
            nms <- c("X", "Y", "Z", "U", "V", "W", "A", "B", "C")

            # reuse letters when necessary
            ind <- seq_len(sum(mis)) %% length(nms)
            ind[ind == 0L] <- length(nms)

            # make sure names are unique
            args$name[mis] <- setdiff(
                make.unique(c(args$name[!mis], nms[ind]), sep = "_"),
                args$name[!mis]
            )
        }
        as_df(args)
    })

    # check ellipsis
    node_dots <- xml2::xml_find_all(node_funs, "Ellipsis", flatten = FALSE)
    funs$ellipsis <- lengths(node_dots) > 0L

    # only include non-static functions
    funs <- funs[is.na(funs$static), ]
    funs$static <- NULL

    funs
}

correct_struct_names <- function(structs, types, fields = NULL) {
    # NOTE: It is possible that some enums/structs/unions have empty names
    #       in the XML. Should use Typedef to get the full names
    structs$name[is.na(structs$name)] <- ""
    if (any(empty <- structs$name == "")) {
        # this is the gccxml output
        if (is.null(types$elaborated)) {
            ids <- structs$id
            ind <- which(empty)
        # check to see if there are any elaborated types
        # If there are elaborated types, this is the CastXML format.
        # The elaborated types should be used to find the actual typedefs
        } else {
            ind <- match(structs$id[empty], types$elaborated$type)
            ids <- rep(NA_character_, length(ind))
            ids[!is.na(ind)] <- types$elaborated$id[ind[!is.na(ind)]]
        }

        ind <- match(ids, types$def$type)
        structs$name[which(empty)[!is.na(ind)]] <- types$def$name[ind[!is.na(ind)]]

        # check again and try to match using fields
        # this is the case when a struct is a field of another struct, e.g.:
        #
        # struct {
        #     struct {
        #         ...
        #     } ABC
        # }
        if (any(empty <- structs$name == "") && !is.null(fields)) {
            if (is.null(types$elaborated)) {
                ind <- which(empty)
            } else {
                ind <- match(structs$id[empty], types$elaborated$type)
            }
            ind <- match(ids[ind], fields$type)
            structs$name[which(empty)[!is.na(ind)]] <- fields$name[ind[!is.na(ind)]]
        }

        # Remaining empty names are anonymous internal types. Keep them unnamed;
        # public dynport output filters them before writing.
    }
    structs
}

proc_node_enums <- function(xml, types, files = NULL) {
    node_enums <- xml2::xml_find_all(xml, "Enumeration")
    enums <- node_attrs(node_enums,
        attrs = c("id", "name", "context", "size", "align", "file")
    )
    if (is.null(enums)) return(NULL)

    # exclude clang auto-generated data
    enums <- enums[!enums$file %in% proc_node_builtin(xml), ]

    # fill all enum names
    enums <- correct_struct_names(enums, types)

    enums$size <- bits_to_bytes(enums$size)
    enums$align <- bits_to_bytes(enums$align)

    report <- empty_report()
    enum_vals <- node_attrs(node_enums, "EnumValue", c("name", "init"), df = FALSE)
    enums$values <- vector("list", nrow(enums))
    for (i in seq_len(nrow(enums))) {
        val <- .subset2(enum_vals, i)
        # check if init value is not an integer
        init <- suppressWarnings(as.integer(val$init))
        if (anyNA(init)) {
            bad <- is.na(init)
            file <- enums$file[[i]]
            if (!is.null(files)) file <- files$name[match(file, files$id)]
            report <- combine_reports(report, new_report(
                "unsupported_enum_value", val$name[bad], file,
                sprintf(
                    "enum member value cannot be represented as an R integer and was not written: %s",
                    val$init[bad]
                )
            ))
            keep <- !is.na(init)
            val$name <- val$name[keep]
            val$init <- val$init[keep]
            init <- init[keep]
        }
        enums$values[[i]] <- df(name = val$name, init = init)
    }

    enums <- enums[, c("id", "name", "values", "size", "align", "file")]
    attr(enums, "report") <- report
    enums
}

proc_node_structs_unions <- function(xml, kind = c("struct", "union"), types, fields) {
    kind <- switch(match.arg(kind), struct = "Struct", union = "Union")
    structs <- node_attrs(xml, kind,
        c("id", "name", "context", "file", "members", "size", "align")
    )
    if (is.null(structs)) return(NULL)

    # exclude clang auto-generated data
    structs <- structs[!structs$file %in% proc_node_builtin(xml), ]

    # fill all struct names
    structs <- correct_struct_names(structs, types, fields)

    # CastXML reports size and alignment in bits
    structs$size <- bits_to_bytes(structs$size)
    structs$align <- bits_to_bytes(structs$align)

    # extract field info if not provided
    if (missing(fields) || NROW(fields)) fields <- proc_node_fields(xml)

    # get field member list
    members <- strsplit(structs$members, " ", fixed = TRUE)
    ignored_members <- c(
        xml2::xml_attr(xml2::xml_find_all(xml, "Unimplemented"), "id"),
        xml2::xml_attr(xml2::xml_find_all(xml, "IndirectField"), "id")
    )
    ignored_members <- ignored_members[!is.na(ignored_members)]

    # cache for all structs and unions id/name
    # needed only when there are members that are another structs or unions
    structs_unions <- NULL

    for (i in seq_len(nrow(structs))) {
        mem <- members[[i]]
        mem <- mem[!mem %in% ignored_members]

        # if there is no members, remove member data of that struct
        if (!length(mem) || (length(mem) == 1L && is.na(mem))) {
            structs$members[i] <- list(NULL)
            next
        }

        # get current struct id
        ctx <- structs$id[[i]]

        # try match members in all fields
        ind <- match(mem, fields$id)

        # handle the simple case where all members can be found in the fields
        if (!any(mis <- is.na(ind))) {
            # check if matched fields have mismatched context
            # should be a rare case
            if (any(wrg <- fields$context[ind] != ctx)) {
                stop(spaste(
                    "Internal error: found fields from mismatched context for",
                    "%s '%s' (id: '%s'): ['%s' (ctx: '%s')]",
                    .vcoll = ", ", .v = list(
                        tolower(kind), structs$name[i], ctx, mem[wrg],
                        fields$context[ind][wrg]
                    )
                ))
            }

            structs$members[i] <- list(df(
                id = mem, name = fields$name[ind], type = fields$type[ind],
                offset = fields$offset[ind], bits = fields$bits[ind]
            ))
        # NOTE: it is possible that structs contain struct/union fields or vice versa
        } else {
            # check if matched fields have mismatched context
            # should be a rare case
            if (any(wrg <- fields$context[ind[!mis]] != ctx)) {
                stop(spaste(
                    "Internal error: found fields from mismatched context for",
                    "%s '%s' (id: '%s'): ['%s' (ctx: '%s')]",
                    .vcoll = ", ", .v = list(
                        tolower(kind), structs$name[i], ctx, mem[!mis[wrg]],
                        fields$context[ind[!mis]][wrg]
                    )
                ))
            }

            # init
            nms <- tps <- rep(NA_character_, length(mem))
            ofs <- bts <- rep(NA_integer_, length(mem))

            nms[!mis] <- fields$name[ind[!mis]]
            tps[!mis] <- fields$type[ind[!mis]]
            ofs[!mis] <- fields$offset[ind[!mis]]
            bts[!mis] <- fields$bits[ind[!mis]]

            # extract unions only when needed
            if (is.null(structs_unions)) {
                # TODO: processing structs needs unions data, and vice versa
                #       both struct and union node extractions have to run twice
                #       should find a more efficient approach
                kind_other <- switch(kind, Struct = "Union", Union = "Struct")
                unions <- node_attrs(xml, kind_other, c("id", "name"))
                unions <- correct_struct_names(unions, types, fields)

                structs_unions <- df(
                    id = c(structs$id, unions$id),
                    name = c(structs$name, unions$name)
                )
            }

            # match using both structs and unions
            ind_union <- match(mem[mis], structs_unions$id)

            # TODO: handle non-typedef'd enum within struct definition, e.g.:
            #
            # typedef struct {
            #   enum {A, B, C} kind;
            # } mystruct
            #
            # should be a rare case

            # stop if still no matched
            if (any(mis_union <- is.na(ind_union))) {
                stop(spaste(
                    "Internal error: found fields with no corresponding field data for",
                    "%s '%s' (id: '%s'): ['%s']",
                    .vcoll = ", ", .v = list(
                        tolower(kind), structs$name[i], ctx, mem[mis][mis_union]
                    )
                ))
            }

            # update member names
            nms[mis] <- structs_unions$name[ind_union]
            # use the struct/union id as the type
            tps[mis] <- structs_unions$id[ind_union]

            # If there are non-typedef'd struct/union inside, there will be two
            # same members:
            # (1) one for <Struct />, i.e. the non-typedef'd struct itself
            # (2) one for <Field /> which refers the above struct
            #
            # In this case, only keep the <Field /> element

            # the indices of which are nested structs/unions
            idx <- which(mis)
            # ids of the nested structs/unions
            pre <- structs_unions$id[ind_union]
            # ids of the following fields
            nxt <- tps[idx + 1L]
            # in case the type refers to an elaborated one
            if (!is.null(types$elaborated)) {
                nxt <- types$elaborated$type[match(nxt, types$elaborated$id)]
            }

            # check if there are no following fields
            if (any(no <- is.na(nxt))) {
                # ignore
                idx <- idx[!no]
                pre <- pre[!no]
                nxt <- nxt[!no]
            }

            # remove the duplicated <Struct />
            rem <- idx[which(pre == nxt)]
            if (length(rem)) {
                mem <- mem[-rem]
                nms <- nms[-rem]
                tps <- tps[-rem]
                ofs <- ofs[-rem]
                bts <- bts[-rem]
            }

            # update member data
            structs$members[i] <- list(df(id = mem, name = nms, type = tps, offset = ofs, bits = bts))
        }
    }

    structs
}

proc_node_structs <- function(xml, types, fields) {
    proc_node_structs_unions(xml, "struct", types, fields)
}

proc_node_unions <- function(xml, types, fields) {
    proc_node_structs_unions(xml, "union", types, fields)
}

proc_node_types <- function(xml) {
    type_def <- node_attrs(xml, "Typedef", c("id", "name", "type", "file", "context"))

    type_base <- node_attrs(xml, "FundamentalType", c("id", "name", "size", "align"))

    type_cvqualified <- node_attrs(xml, "CvQualifiedType", c("id", "type", "const"))

    type_atomic <- node_attrs(xml, "AtomicType", c("id", "type"))

    type_auto <- node_attrs(xml, "AutoType", c("id"))

    type_pointer <- node_attrs(xml, "PointerType", c("id", "type"))

    type_offset <- node_attrs(xml, "OffsetType", c("id", "type", "basetype"))

    type_reference <- node_attrs(xml, "ReferenceType", c("id", "type"))

    type_rvalueref <- node_attrs(xml, "RValueReferenceType", c("id", "type"))

    type_array <- node_attrs(xml, "ArrayType", c("id", "type", "min", "max"))

    type_elaborated  <- node_attrs(xml, "ElaboratedType",
        c("id", "type", "keyword", "qualifier")
    )

    node_funt <- xml2::xml_find_all(xml, "FunctionType")
    type_function <- node_attrs(node_funt, attrs = c("id", "returns"))
    if (!is.null(type_function)) {
        type_function$arguments <- node_attrs(node_funt, "Argument", "type", df = FALSE)
        node_dots <- xml2::xml_find_all(node_funt, "Ellipsis", flatten = FALSE)
        type_function$ellipsis <- lengths(node_dots) > 0L
    }

    list(
        def         = type_def,
        base        = type_base,
        cvqualified = type_cvqualified,
        atomic      = type_atomic,
        pointer     = type_pointer,
        offset      = type_offset,
        reference   = type_reference,
        rvalueref   = type_rvalueref,
        auto        = type_auto,
        array       = type_array,
        elaborated  = type_elaborated,
        func        = type_function
    )
}

bits_to_bytes <- function(x) {
    x <- suppressWarnings(as.integer(x))
    x[!is.na(x)] <- as.integer(x[!is.na(x)] / 8L)
    x
}

format_array_type <- function(array) {
    min <- suppressWarnings(as.integer(array$min))
    max <- suppressWarnings(as.integer(array$max))
    len <- max - min + 1L
    len[is.na(len) | len < 1L] <- NA_integer_
    ifelse(is.na(len), "[]", sprintf("[%d]", len))
}

filter_rdyncall_output <- function(data, files = NULL) {
    report <- empty_report()

    file_names <- function(file) {
        if (is.null(files) || is.null(file)) return(rep(NA_character_, length(file)))
        out <- files$name[match(file, files$id)]
        out[is.na(out)] <- NA_character_
        out
    }

    valid_export_name <- function(name) {
        !is.na(name) & nzchar(name) & name == make.names(name)
    }

    type_references_valid_names <- function(type) {
        if (!inherits(type, "dynporttype")) return(TRUE)
        named <- type$kind %in% c("enum", "struct", "union")
        names <- gsub("^<(.*)>$", "\\1", type$type[named])
        !any(!valid_export_name(names))
    }

    type_has_writable_signature <- function(type, empty = FALSE, array = FALSE) {
        dyncall_sig(type, empty = empty, array = array)
        type_references_valid_names(type)
    }

    filter_export_names <- function(df, field) {
        if (is.null(df)) return(df)
        keep <- valid_export_name(df$name)
        if (any(!keep)) {
            report <<- combine_reports(report, new_report(
                "unsupported_export_name", df$name[!keep], file_names(df$file[!keep]),
                sprintf("%s name is not a valid R export name and was not written", field)
            ))
        }
        as_df(df[keep, , drop = FALSE])
    }

    filter_function_signatures <- function(df, field) {
        if (is.null(df)) return(df)
        keep <- vapply(seq_len(nrow(df)), function(i) {
            ret <- df$returns[[i]]
            if (!inherits(ret, "dynporttype") && !is.null(ret$type)) ret <- ret$type
            args <- df$arguments[[i]]
            arg_types <- if (!length(args)) list() else args$type

            !inherits(try({
                if (!type_has_writable_signature(ret, empty = TRUE)) stop("invalid type name")
                ok <- vapply(arg_types, type_has_writable_signature, logical(1), empty = FALSE)
                if (any(!ok)) stop("invalid type name")
            }, silent = TRUE), "try-error")
        }, logical(1))
        if (any(!keep)) {
            report <<- combine_reports(report, new_report(
                "unsupported_signature", df$name[!keep], file_names(df$file[!keep]),
                sprintf("%s signature cannot be written as a rdyncall dynport signature", field)
            ))
        }
        as_df(df[keep, , drop = FALSE])
    }

    filter_aggregate_signatures <- function(df, field) {
        if (is.null(df)) return(df)
        keep <- vapply(seq_len(nrow(df)), function(i) {
            mem <- df$members[[i]]
            if (!length(mem$type)) return(TRUE)
            !inherits(try({
                ok <- vapply(
                    mem$type, type_has_writable_signature, logical(1),
                    empty = FALSE, array = TRUE
                )
                if (any(!ok)) stop("invalid type name")
            }, silent = TRUE), "try-error")
        }, logical(1))
        if (any(!keep)) {
            report <<- combine_reports(report, new_report(
                "unsupported_signature", df$name[!keep], file_names(df$file[!keep]),
                sprintf("%s member signature cannot be written as a rdyncall dynport signature", field)
            ))
        }
        as_df(df[keep, , drop = FALSE])
    }

    filter_enum_members <- function(df) {
        if (is.null(df)) return(df)
        for (i in seq_len(nrow(df))) {
            values <- df$values[[i]]
            keep <- valid_export_name(values$name)
            if (any(!keep)) {
                report <<- combine_reports(report, new_report(
                    "unsupported_export_name", values$name[!keep], file_names(df$file[[i]]),
                    sprintf("enum member of '%s' is not a valid R export name and was not written", df$name[[i]])
                ))
                df$values[[i]] <- values[keep, , drop = FALSE]
            }
        }
        df
    }

    for (field in c("Function", "Variadic", "FuncPtr")) {
        data[[field]] <- filter_function_signatures(data[[field]], field)
        data[[field]] <- filter_export_names(data[[field]], field)
    }

    for (field in c("Enum", "Struct", "Union")) {
        data[[field]] <- filter_export_names(data[[field]], field)
    }
    for (field in c("Struct", "Union")) {
        data[[field]] <- filter_aggregate_signatures(data[[field]], field)
    }
    data$Enum <- filter_enum_members(data$Enum)

    list(data = data, report = report)
}

pull_report <- function(data) {
    report <- attr(data, "report", exact = TRUE)
    attr(data, "report") <- NULL
    list(data = data, report = combine_reports(report))
}

empty_report <- function() {
    data.frame(
        kind = character(), name = character(), file = character(),
        line = integer(), message = character(),
        stringsAsFactors = FALSE
    )
}

new_report <- function(kind, name, file, message, line = NA_integer_) {
    if (!length(name)) return(empty_report())
    file <- rep_len(file, length(name))
    message <- rep_len(message, length(name))
    line <- rep_len(as.integer(line), length(name))
    data.frame(
        kind = kind, name = name, file = file, line = line, message = message,
        stringsAsFactors = FALSE
    )
}

normalize_report <- function(report) {
    if (is.null(report) || !nrow(report)) return(empty_report())

    if (!"kind" %in% names(report)) report$kind <- character(nrow(report))
    if (!"name" %in% names(report)) report$name <- character(nrow(report))
    if (!"file" %in% names(report)) report$file <- character(nrow(report))
    if (!"line" %in% names(report)) report$line <- NA_integer_
    if (!"message" %in% names(report)) report$message <- character(nrow(report))

    report$line <- as.integer(report$line)
    report[names(empty_report())]
}

combine_reports <- function(...) {
    reports <- list(...)
    reports <- reports[!vapply(reports, is.null, logical(1))]
    if (!length(reports)) return(empty_report())
    reports <- lapply(reports, normalize_report)
    out <- do.call(rbind, reports)
    row.names(out) <- NULL
    out
}

scan_castxml_function_like_macros <- function(header, cflags, castxml, dirs = NULL, pattern = NULL) {
    defines <- run_castxml_preprocessor(castxml, "-dD", header, cflags)
    active <- run_castxml_preprocessor(castxml, "-dM", header, cflags)
    report <- empty_report()

    if (!defines$ok || !active$ok) {
        failed <- c(if (!defines$ok) "-dD", if (!active$ok) "-dM")
        report <- combine_reports(report, new_report(
            "macro_scan_failed", failed, normalizePath(header, mustWork = FALSE),
            c(defines$message, active$message)[c(!defines$ok, !active$ok)]
        ))
    }
    if (!defines$ok || !active$ok) return(report)

    candidates <- parse_castxml_macro_definitions(defines$output)
    active_names <- parse_function_like_macro_names(active$output)
    if (!nrow(candidates) || !length(active_names)) return(report)

    candidates <- candidates[candidates$name %in% active_names, , drop = FALSE]
    if (!nrow(candidates)) return(report)

    candidates <- candidates[!duplicated(candidates$name, fromLast = TRUE), , drop = FALSE]
    candidates <- filter_macro_candidates(candidates, dirs, pattern)
    if (!nrow(candidates)) return(report)

    combine_reports(report, new_report(
        "unsupported_macro", candidates$name, candidates$file,
        "function-like macro found in CastXML preprocessor output; dynport callable entry was not generated",
        candidates$line
    ))
}

run_castxml_preprocessor <- function(castxml, mode, header, cflags) {
    out <- tryCatch(
        withCallingHandlers(
            system3(castxml, "-E", mode, cflags, header, .capture = TRUE),
            warning = function(w) invokeRestart("muffleWarning")
        ),
        error = function(e) e
    )
    if (inherits(out, "error")) {
        return(list(ok = FALSE, output = character(), message = conditionMessage(out)))
    }

    status <- attr(out, "status", exact = TRUE)
    if (!is.null(status) && status != 0L) {
        message <- sprintf("CastXML preprocessor %s failed with status %s.", mode, status)
        return(list(ok = FALSE, output = out, message = message))
    }

    list(ok = TRUE, output = out, message = NA_character_)
}

parse_function_like_macro_names <- function(lines) {
    if (!length(lines)) return(character())
    m <- regexec("^#\\s*define\\s+([A-Za-z_][A-Za-z0-9_]*)\\(", lines, perl = TRUE)
    hit <- regmatches(lines, m)
    hit <- hit[lengths(hit) > 1L]
    unique(vapply(hit, `[[`, character(1), 2L))
}

parse_castxml_macro_definitions <- function(lines) {
    if (!length(lines)) {
        return(data.frame(name = character(), file = character(), line = integer()))
    }

    current_file <- NA_character_
    current_line <- NA_integer_
    names <- files <- character()
    line_numbers <- integer()

    for (line in lines) {
        marker <- regexec("^#\\s+(?:line\\s+)?([0-9]+)\\s+\"([^\"]+)\"", line, perl = TRUE)
        marker_hit <- regmatches(line, marker)[[1L]]
        if (length(marker_hit) > 2L) {
            current_line <- as.integer(marker_hit[[2L]])
            current_file <- marker_hit[[3L]]
            next
        }

        macro <- regexec("^#\\s*define\\s+([A-Za-z_][A-Za-z0-9_]*)\\(", line, perl = TRUE)
        macro_hit <- regmatches(line, macro)[[1L]]
        if (length(macro_hit) > 1L && is_real_preprocessor_file(current_file)) {
            names <- c(names, macro_hit[[2L]])
            files <- c(files, normalizePath(current_file, mustWork = FALSE))
            line_numbers <- c(line_numbers, current_line)
        }

        if (!is.na(current_line)) current_line <- current_line + 1L
    }

    data.frame(name = names, file = files, line = line_numbers, stringsAsFactors = FALSE)
}

is_real_preprocessor_file <- function(file) {
    is_string(file) && nzchar(file) && !startsWith(file, "<") && file.exists(file)
}

filter_macro_candidates <- function(candidates, dirs = NULL, pattern = NULL) {
    if (!nrow(candidates)) return(candidates)

    if (!is.null(dirs)) {
        dirs <- normalizePath(dirs, mustWork = FALSE)
        paths <- normalizePath(dirname(candidates$file), mustWork = FALSE)
        keep <- logical(length(paths))
        for (d in dirs) keep <- is_parent_dir(d, paths) | keep
        candidates <- candidates[keep, , drop = FALSE]
    }

    if (!is.null(pattern) && nrow(candidates)) {
        candidates <- candidates[grepl(pattern, candidates$name), , drop = FALSE]
    }

    candidates
}

mark_unsupported_layouts <- function(df, kind, files) {
    if (is.null(df) || !nrow(df)) return(list(data = df, report = empty_report()))

    unsupported_type <- vapply(df$members, member_has_unsupported_signature, logical(1))
    unsupported_layout <- vapply(seq_len(nrow(df)), function(i) {
        is_unsupported_layout(kind, df$size[[i]], df$align[[i]], df$members[[i]])
    }, logical(1))
    unsupported <- unsupported_type | unsupported_layout

    if (!any(unsupported)) return(list(data = df, report = empty_report()))

    report <- combine_reports(
        new_report(
            "unsupported_type", df$name[unsupported_type],
            files$name[match(df$file[unsupported_type], files$id)],
            "aggregate member type cannot be written as a rdyncall signature; emitted as opaque"
        ),
        new_report(
            "unsupported_layout", df$name[unsupported_layout & !unsupported_type],
            files$name[match(df$file[unsupported_layout & !unsupported_type], files$id)],
            "aggregate layout cannot be expressed with rdyncall layout directives; emitted as opaque"
        )
    )
    df$members[unsupported] <- replicate(sum(unsupported), NULL, simplify = FALSE)
    list(data = df, report = report)
}

node_attrs <- function(nodes, name = NULL, attrs = c("id", "name"), df = TRUE) {
    if (!is.null(name)) {
        nodes <- xml2::xml_find_all(nodes, name, flatten = FALSE)
    }
    if (!length(nodes)) return(NULL)

    if (is.null(attrs)) {
        attrs <- names(xml2::xml_attrs(nodes[[1]]))
        if (!length(attrs)) return(NULL)
    }

    if (is.null(names(attrs))) {
        names(attrs) <- attrs
    } else {
        names(attrs)[names(attrs) == ""] <- attrs[names(attrs) == ""]
    }

    res <- lapply(nodes, function(type) lapply(attrs, xml2::xml_attr, x = type))
    if (!df) res else as_df(transpose(res))
}

#' Print summary of an `dynport` object
#'
#' @param x A `dynport`.
#'
#' @param n The number of items to print. Default: `5`.
#'
#' @param ... Other arguments to pass. Reserved for future use.
#'
#' @return `x` invisibly.
#'
#' @export
print.dynport <- function(x, n = 5L, ...) {
    stopifnot(is_count(n))
    for (elem in x[names(x) != "File"]) print(elem, n = n)
    invisible(x)
}
